conky.config = {
    out_to_wayland = true,
    out_to_x = false,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    double_buffer = true,
    update_interval = 1,
    net_avg_samples = 2,
    no_buffers = true,

    use_xft = true,
    font = 'Sans Serif:size=10',
    xftalpha = 1,
    override_utf8_locale = true,
    uppercase = false,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,

    default_color = 'D9DEE7',
    color1 = '78A9FF',
    color2 = 'AAB2BF',

    minimum_width = 300,
    maximum_width = 300,
    minimum_height = 190,

    alignment = 'top_left',
    gap_x = 34,
    gap_y = 570,

    border_inner_margin = 14,
};

conky.text = [[
${voffset 6}${color1}Redes${color}
${color2}${hr 1}${color}

IP${alignr}${addr wlp2s0}
Bajada${alignr}${downspeedf wlp2s0} KiB/s
Subida${alignr}${upspeedf wlp2s0} KiB/s

${voffset 10}${color1}Batería${color}
${color2}${hr 1}${color}

Battery${alignr}${battery_percent BAT0}%
Estado${alignr}${battery_status}
]];
