# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para bloquear la sesión
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Encender pantalla al despertar
}

# 1. Bajar brillo (ahorro de energía)
listener {
    timeout = 150                                # 2.5 min
    on-timeout = brightnessctl -s set 10         # Brillo al mínimo
    on-resume = brightnessctl -r                # Restaurar brillo
}

# 2. Bloquear pantalla
listener {
    timeout = 300                                # 5 min
    on-timeout = loginctl lock-session           # Llama a lock_cmd definido arriba
}

# 3. Apagar monitor (DPMS)
listener {
    timeout = 330                                # 5.5 min
    on-timeout = hyprctl dispatch dpms off       # Apaga la señal de video
    on-resume = hyprctl dispatch dpms on         # La enciende al mover el ratón
}

# 4. Suspender PC
listener {
    timeout = 1800                               # 30 min
    on-timeout = systemctl suspend               # Suspender sistema
}
